#!/bin/bash

#-----------------------------------------------------------------------------
#
# File: uni_sign
#
# Description:
#	This script takes input file as argument and is used to sign the
#	ISBC/ESBC Images specified in the input file for Platform specified.
#	For doing this the required CST Tools are invoked with the
#	input file as argument
#
#		Copyright (c) 2015 Freescale Semiconductor, Inc.
#		Freescale Proprietary.
#
#-----------------------------------------------------------------------------

# Help Function
print_help() {
	./create_hdr_isbc --help
	echo "-----------------------------------------------------"
	echo "- uni_sign is a wrapper script over the TOOL"
	echo "- Correct Usage (OPtions as specified above):"
	echo "-"
	echo "- $0 [options] <input_file>"
	echo "-"
	echo "-----------------------------------------------------"
	exit
}

############################################################
# Script Starts Here
############################################################
echo ""

# Check if proper arguments are specified

if [ $# -eq 0 ]; then
	# Invalid Arguments
	echo "Error !! Invalid Usage"
	print_help

elif [ $1 == "--help" ]; then
	# Help Message to be printed
	print_help

else 
	input_file=${@:$#}

	# Check if Input File exists
	if [ -s $input_file ]; then
		# Check if image is ESBC or ISBC
		grep "^ESBC=1$" $input_file &> /dev/null

	else
		echo "Input File $input_file does not exist"
		print_help
	fi

	#########################################################
	# IF ESBC = 1, call create_hdr_esbc
	# Else Call create_hdr_isbc
	#########################################################

	if [ $? -eq 0 ]; then
		./create_hdr_esbc $@
	else
		./create_hdr_isbc $@
	fi

fi
